config/routes.rb
Rails.application.routes.draw do
  resources :websites do
    collection do
      post :find
    end

    resources :articles do
      member do
        post :action
      end
    end
  end

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  root 'pages#home'
end

app/models/action.rb
class Action < ActiveRecord::Base
  validates :action_type, presence: true

  has_one :article
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :url, presence: true

  has_one :website
  has_many :actions, dependent: :destroy
end

app/models/website.rb
class Website < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true

  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_website
  before_action :find_article, only: [:action, :show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:action]

  def index
    @websites = Article.all
  end

  def action
    @article.actions.create(action_type: params[:action_type], paragraph: params[:paragraph])

    respond_to do |format|
      format.json { render json: @article.actions }
    end
  end

  def show
    @body = @article.body
    @paragraphs = @body.split(/(<\/p>)/).each_slice(2).map(&:join)
  end

  def new
    @website = Article.new
  end

  def edit
  end

  def create
    @website = Article.create(website_params)
    redirect_to website_path(@website)
  end

  def update
    @website.update_attributes(website_params)
    redirect_to website_path(@website)
  end

  def destroy
    @website.destroy
    redirect_to websites_path
  end

  private

  def find_website
    @website = Website.find(params[:website_id])
  end

  def find_article
    @article = @website.articles.where(id: params[:id]).first
  end

  def website_params
    params.require(:website).permit(:name, :url, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :find_website, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:find]

  def find
    find_or_create_website
    find_or_create_article

    respond_to do |format|
      format.json { render json: [@website, @article, @article.actions] }
    end
  end

  def index
    @websites = Website.all
  end

  def show
  end

  def new
    @website = Website.new
  end

  def edit
  end

  def create
    @website = Website.create(website_params)
    redirect_to website_path(@website)
  end

  def update
    @website.update_attributes(website_params)
    redirect_to website_path(@website)
  end

  def destroy
    @website.destroy
    redirect_to websites_path
  end

  private

  def find_website
    @website = Website.find(params[:id])
  end

  def find_or_create_website
    if Website.where(url: params[:url]).any?
      @website = Website.where(url: params[:url]).first
    else
      @website = Website.create!(name: params[:url], url: params[:url])
    end
  end

  def find_or_create_article
    if Article.where(url: params[:href]).any?
      @article = @website.articles.where(url: params[:href]).first
    else
      @article = @website.articles.create!(url: params[:href], body: params[:body], title: params[:title])
    end
  end

  def website_params
    params.require(:website).permit(:name, :url, :background_colour, :foreground_colour, :position, :offset)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %></h1>
  <%= link_to "Read on #{@website.name}", @article.url %>
</div>

<div class="container double-width">

  <% @paragraphs.each_with_index do |paragraph, index| %>
    <div class="side-by-side">
      <div class="side-by-side-paragraph">
        <%= raw paragraph %>
      </div>
      <div class="side-by-side-paragraph">
        <ul>
          <li>Tell me more: <%= @article.actions.where(action_type: "tell_me_more", paragraph: index).count %></li>
          <li>Make it clearer: <%= @article.actions.where(action_type: "make_it_clearer", paragraph: index).count %></li>
          <li>Prove it: <%= @article.actions.where(action_type: "prove_it", paragraph: index).count %></li>
      </div>
    </div>
  <% end %>
</div>

<%= content_for :menu do %>
  <li><%= link_to "Articles", website_path(@website) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HearMe</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>-<%= action_name %>">
  <%= render partial: "shared/menu_bar" %>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    <%= raw(content_for(:js_page).presence || "WN.page = new WN.BasePage;") %>
  <% end %>

</body>
</html>

app/views/pages/home.html.erb
  <div class="heading container">
    <div class="logo">
      <?xml version='1.0' encoding='utf-8'?>
      <svg style='fill: #D8352A' version='1.1' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 200 200' style='enable-background:new 0 0 200 200;' xml:space='preserve'>
        <path class='st0' d='M162.4,175.3l-30.2-23.5H30.9c-9,0-16.1-7.3-16.1-16.1V60.1c0-9,7.3-16.1,16.1-16.1h137.7c9,0,16.1,7.3,16.1,16.1v75.5c0,9-7.3,16.1-16.1,16.1h-6.1L162.4,175.3z M30.9,52.4c-4.2,0-7.7,3.5-7.7,7.7v75.5c0,4.2,3.5,7.7,7.7,7.7h106l17,12.9v-12.9h14.7c4.2,0,7.7-3.5,7.7-7.7V60.1c0-4.2-3.5-7.7-7.7-7.7H30.9z M124.5,93.9H104V73.4h-8.4v20.5H75.1v8.4h20.5v20.5h8.4v-20.5h20.5V93.9z'/>
      </svg>
    </div>
  </div>


<%= content_for :menu do %>
  <li><%= link_to "Websites", websites_path %></li>
<% end %>

app/views/shared/_menu_bar.html.erb
<nav class="menu-bar">
  <?xml version='1.0' encoding='utf-8'?>
  <svg style='fill: #D8352A' version='1.1' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 200 200' style='enable-background:new 0 0 200 200;' xml:space='preserve'>
    <path class='st0' d='M162.4,175.3l-30.2-23.5H30.9c-9,0-16.1-7.3-16.1-16.1V60.1c0-9,7.3-16.1,16.1-16.1h137.7c9,0,16.1,7.3,16.1,16.1v75.5c0,9-7.3,16.1-16.1,16.1h-6.1L162.4,175.3z M30.9,52.4c-4.2,0-7.7,3.5-7.7,7.7v75.5c0,4.2,3.5,7.7,7.7,7.7h106l17,12.9v-12.9h14.7c4.2,0,7.7-3.5,7.7-7.7V60.1c0-4.2-3.5-7.7-7.7-7.7H30.9z M124.5,93.9H104V73.4h-8.4v20.5H75.1v8.4h20.5v20.5h8.4v-20.5h20.5V93.9z'/>
  </svg>
  <ul>
    <%= content_for :menu %>
  </ul>
</nav>

app/views/websites/_form.html.erb
<%= simple_form_for @website do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.input :position %>
  <%= f.input :offset %>
  <%= f.input :background_colour, input_html: { class: "jscolor" } %>
  <%= f.input :foreground_colour, input_html: { class: "jscolor" } %>
  <%= f.submit %>
<% end %>

app/views/websites/edit.html.erb
<div class="container">
  <h1>Edit Website</h1>

  <%= render partial: "form" %>
  <%= button_to "Delete", website_path(@website), method: :delete, class: "button" %>
</div>

<%= content_for :menu do %>
  <li><%= link_to "Back", websites_path %></li>
<% end %>

app/views/websites/index.html.erb
<div class="container">
  <ul>
    <% @websites.each do |website| %>
      <li><%= link_to website.name, website_path(website) %></li>
    <% end %>
  </ul>
</div>

<%= content_for :menu do %>
  <li><%= link_to "Websites", websites_path %></li>
  <li><%= link_to "New Website", new_website_path %></li>
<% end %>

app/views/websites/new.html.erb
<div class="container">
  <h1>New Website</h1>

  <%= render partial: "form" %>
</div>

<%= content_for :menu do %>
  <li><%= link_to "Back", websites_path %></li>
<% end %>

app/views/websites/show.html.erb
<div class="container">
  <h1><%= @website.name %></h1>
  <h2><%= @website.url %></h2>

  <ul>
    <% @website.articles.each do |article| %>
      <li><%= link_to article.title, website_article_path(@website, article) %></li>
    <% end %>
  </ul>
</div>

<%= content_for :menu do %>
  <li><%= link_to "Edit Website", edit_website_path(@website) %></li>
  <li><%= link_to "Websites", websites_path %></li>
<% end %>